### PR TITLE
data: NVIDIA GP107M [GeForce GTX 1050 Mobile]

### PR DESCRIPTION
**Pull request by kyrios123**

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Could I be a pain please? Could you do this with both the Intel **and** the NVIDIA in the same file? Just pass both PCI paths - this way I'll have more data to work with =)

**Comment by kyrios123** [comment]
Is it okay now ?

**Comment by ikeydoherty** [comment]
perfect, thank you!

**Comment by ikeydoherty** [comment]
Should probably merge this huh

**Pull request merged**
